projects:
  MessengerRN:
    schemaPath: amplify/backend/api/MessengerRN/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/index.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 10
